apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetcore-app
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dotnetcore-app
  template:
    metadata:
      labels:
        app: dotnetcore-app
        tier: dotnetcore-app
    spec:
     containers:
     - name: dotnetcore-app
       image: docsearce/dotnetcore:latest
       imagePullPolicy: Always
       ports:
          - containerPort: 5000
            name: dotnetcore-app
            
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetcore-app
  labels:
    app: dotnetcore-app
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: dotnetcore-app
    tier: dotnetcore-app
  type: LoadBalancer
